### ISSUE TITLE
cannot stop sync

### ISSUE THREAD

**Issue by bryanfok** [thisboyiscrazy/vscode-rsync#10]
I cannot stop sync. I tried terminate from the command, or shut down code itself.

**Comment by thisboyiscrazy** [comment]
Currently there is no way, I will add a stop button.

**Comment by thisboyiscrazy** [comment]
I tried adding a stop button. it did send a kill command to rsync. Rsync then seems to ignore the signal.

I can not fix it until https://github.com/mattijs/node-rsync/issues/57 is resolved.

**Comment by thisboyiscrazy** [comment]
There is now a status bar item in the lower left that can be used to kill the sync.

**Comment by thisboyiscrazy** [comment]
Should be fixed to b29364b56be65d018fb47670710a9c263e281e90 with a few caveats.
