### ISSUE TITLE
how to use this extension?

### ISSUE THREAD

**Issue by CarryOnHxy** [thisboyiscrazy/vscode-rsync#102]
i think the document is not friend,just want to know the step of usage

**Comment by thisboyiscrazy** [comment]
Easiest is just configure the remote:
```
sync-rsync.remote
```

Then Ctrl+Shift+P (on linux) type "Sync Local to Remote" press enter to sync the local files to the remote site.

**Comment by davidcostadev** [comment]
The big thing is, how to configure it. It's not clear.

**Comment by thisboyiscrazy** [comment]
I would like to make clearer how do use it.

It's really as easy as setting `sync-rsync.remote` then opening the command pallet and running `Sync-Rsync: Sync Local to Remote` or `Sync-Rsync: Sync Remote to local`

I am up for suggestions on changing the documentation.

**Comment by davidcostadev** [comment]
I did a pull request #104 that I think that can help users when they need to configure this extension.
