### ISSUE TITLE
sync is not happening

### ISSUE THREAD

**Issue by bryanfok** [thisboyiscrazy/vscode-rsync#11]
I use the command `sync-rsync: Local to Remote`. I dont see any output from the Output console. And if I try again it give me error 'Sync - Rsync there is a sync in process'

**Comment by bryanfok** [comment]
and when i click the Syncing (click to kill) there is no response.

**Comment by thisboyiscrazy** [comment]
Are you runnjng Ubuntu / debian?

**Comment by bryanfok** [comment]
I am running on fedora

On Jun 16, 2017 6:32 PM, thisboyiscrazy <notifications@github.com> wrote:
Are you runnjng Ubuntu / debian?

**Comment by thisboyiscrazy** [comment]
can you run the same rsync command from a shell?

**Comment by beanwonder** [comment]
same for me the rsync plugin is no longer working on my mac

it just showing that syncing and never stop and response

and I can  run rsync on my mac to sync

**Comment by thisboyiscrazy** [comment]
Ok i will revert the latest changes and push it out this weekend.

**Comment by thisboyiscrazy** [comment]
@bryanfok or @beanwonder are either one of you able to help me see which commit broke it? I think it is ether 11282ef24d4ce697005d66562ea9720442f4eaa8 or 1b88718ea6e2f746ca8d9ac5f5c3fe6d9399778d

**Comment by cscortes** [comment]
Did this get a fix?  I believe this is still an issue on both Windows and Redhat Linux on the latest version of VS Code 1.7x.x.  The main problem is the "Sync Local to Remote" or the "Sync Remote to Local" menu items do not work.  If you touch a file, then it will kick off a sync correctly.
