### ISSUE TITLE
Unable to Rsync after Window Update

### ISSUE THREAD

**Issue by tnapikoski** [thisboyiscrazy/vscode-rsync#110]
Currently receiving the following errors on "any" file save / full sync:

/usr/bin/rsync: -c: line 0: unexpected EOF while looking for matching `''
/usr/bin/rsync: -c: line 1: syntax error: unexpected end of file

**Comment by weskb** [comment]
On update to Windows Version 2004 I was getting the same error when using rsync via WSL.

Removing 
"sync-rsync.executableShell": "C:\\Windows\\System32\\bash.exe",

from my settings resolved the issue.

**Comment by pvale18** [comment]
I have the same issue after the recently update of Windows. I tried removing "sync-rsync.executableShell": "C:\Windows\System32\bash.exe", from my settings, but now I get an other error:.

ERROR > spawn rsync ENOENT

Please help!

**Comment by thisboyiscrazy** [comment]
are you using cygwin, WSL, or WSL2?

**Comment by pvale18** [comment]
None of them. I was using only Bash on windows.

**Comment by thisboyiscrazy** [comment]
Ok I have never install bash directly on windows where do you get it?

**Comment by pvale18** [comment]
It comes pre-installed in WIndows 10.
