### ISSUE TITLE
Feature Request: multi remote destinations

### ISSUE THREAD

**Issue by AStupidBear** [thisboyiscrazy/vscode-rsync#12]
It will be great if this extension can support multiple remote destinations.

**Comment by thisboyiscrazy** [comment]
Interesting, how would that work with pulling remote to local?

**Comment by AStupidBear** [comment]
```
"sync-rsync.remote": ["remote1", "remote2", ...]
"sync-rsync.local": ["local1", "local2", ...]
```

**Comment by thisboyiscrazy** [comment]
I am interested, but don't fully understand the use case.

Can you elaborate on how this would get used?

**Comment by AStupidBear** [comment]
Sorry for the obscurity of my previous comment. 

I have two local folders "local1" and "local2" and I'd like to sync these folders to two remote servers "remote1" and "remote2" respectively. If "local2" == "local1", then I can achieve syncing one local folder to multiple remote destinations. 

The pseudo Python code is 

```python
for (remote, local) in zip(sync-rsync.remote, sync-rsync.local)
    original_rsync_opreration_of_vscode_rsync(remote, local)
end
```

**Comment by thisboyiscrazy** [comment]
Interesting, it will require a large rewrite of the settings. Which i may
be doing anyway. I will look into it.

**Comment by thisboyiscrazy** [comment]
The biggest issue is a lot of the setting are destination specific (e.g. shell, chown, etc.). The best way to do that would be the make the configuration an array. This would be breaking changes.

**Comment by AStupidBear** [comment]
Thanks! Will try.
