### ISSUE TITLE
Version from Marketplace is not working

### ISSUE THREAD

**Issue by leshniak** [thisboyiscrazy/vscode-rsync#15]
@thisboyiscrazy Build from Marketplace is not working for me right now, it works only when I build extension from sources. No status bar item, commands are not found. Can you confirm?

**Comment by thisboyiscrazy** [comment]
Correct it's not loading for some reason. I'm looking into it.

**Comment by thisboyiscrazy** [comment]
Should be fixed in 041235cf9d70918ec79050b7c46d52b575350759

**Comment by leshniak** [comment]
Yup, fixed.
