### ISSUE TITLE
Sudo Rsync

### ISSUE THREAD

**Issue by rucciva** [thisboyiscrazy/vscode-rsync#19]
How to run sudo rsync on the remote server? `--rsync-path="sudo rsync" `

**Comment by thisboyiscrazy** [comment]
The rsync library I am using does not support it. I opened an issue https://github.com/mattijs/node-rsync/issues/58

**Comment by rucciva** [comment]
isn't this supported by set(option,value) function? [](https://github.com/mattijs/node-rsync#setoption-value)

**Comment by thisboyiscrazy** [comment]
It works but I had to create a sh file on the remote side

```
#!/bin/bash

sudo rsync "$@"
```

then

```
"sync-rsync.options":[
    ["--rsync-path","/home/user/rsync.sh"]
]
```

**Comment by rucciva** [comment]
yup, passing _sudo rsync_ does not work but what odd is that when i copy the complete rsync command from the vscode output after running your plugin,  and paste it in the terminal, the commands actually works

**Comment by cristiandaulisio** [comment]
i have the same problem..someone know how launch rsync with sudo?
