### ISSUE TITLE
How to use the cygwin shell as exexutableShell?

### ISSUE THREAD

**Issue by HeringGitHub** [thisboyiscrazy/vscode-rsync#20]
Setting like as the follow:
"sync-rsync.executableShell": "D:\\cygwin64\\bin\\bash.exe“
It will report error.

"sync-rsync.executableShell": "D:\\cygwin64\\bin\\bash.exe --login"
It will syncing all the time, and the remote host could not receive any file.

**Comment by thisboyiscrazy** [comment]
Are you just trying the run rsync, or are you trying to use bash for things like variable expansion?

**Comment by HeringGitHub** [comment]
After running rsync, the output window will print the rsync command like  as "rsync -rlptzv --progress --exclude=.git --exclude=.vscode --exclude=.svn   /cygdrive/d/... root@x.x.x.x:/home/buildenv/...".
However, nothing has happened.  Then, I copied the command into my cygwin terminal, it works well.

**Comment by thisboyiscrazy** [comment]
I am going to try to replicate the problem.

Have you tried without setting "sync-rsync.executableShell". You don't actually need if rsync is in your %PATH%

**Comment by Ehekatl** [comment]
I have the same problem as well, if I put rsync in my windows path, it gives me:
```
No such file or directory (2)
rsync error: error in IPC code (code 14) at pipe.c(85) [sender=3.1.2]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]
```

**Comment by thisboyiscrazy** [comment]
@Ehekatl That error seems to indicate rsync is not installed on the remote machine.

I am still working on test  the hanging.

**Comment by HeringGitHub** [comment]
@thisboyiscrazy  Whatever setting the "sync-rsync.executableShell", It would not work. The output window just display a rsync command like as the above.  Which default bash will be using? cmd or powershell?

**Comment by msevastian** [comment]
have the same issue on Win 10
@thisboyiscrazy probably in order to make it work, you should pack generated rsync command in a temporary shell file, and then append path of it to path in "sync-rsync.executableShell"

**Comment by msevastian** [comment]
other option, is not to perform rsync in background, but pass execution of rsync command to terminal.
but that is less convenient

**Comment by hvpareja** [comment]
Maybe you know that, but you should scape the "\", i.e.:

`"sync-rsync.executableShell": "D:\\cygwin64\\bin\\bash.exe“`

**Comment by plumps** [comment]
There is definitely something fishy with the plugin on Windows and wsl.

```json
{
    "sync-rsync.delete": true,
    "sync-rsync.executableShell": "C:\\WINDOWS\\system32\\wsl.exe",
    "sync-rsync.shell": "ssh -i /mnt/c/Users/maksb/.ssh/id_rsa",
    "sync-rsync.sites": [
        {
            "localPath": "/mnt/c/Users/maksb/Documents/code/foobar/",
            "remotePath" : "plumps@server:/home/plumps/foobar/",
        },
    ]
}
```
creates the following (hanging and **failing**) output
```
rsync -nrlptzv --progress --rsh="ssh -i /mnt/c/Users/maksb/.ssh/id_rsa" --delete --exclude=.git --exclude=.vscode /mnt/c/Users/maksb/Documents/code/foobar/ plumps@server:/home/plumps/foobar/ 
``` 
Executing the line in powershell prefixed by **wsl** works though!

**Comment by thisboyiscrazy** [comment]
Setting `sync-rsync.executable` to the cygwin rsync executable should fix this.

**Comment by thisboyiscrazy** [comment]
Fexed in f7b4e075f77118c8fd98648ec88d228e96b80455
