### ISSUE TITLE
sync-rsync.compareDown not found

### ISSUE THREAD

**Issue by charlesbodman** [thisboyiscrazy/vscode-rsync#21]
Getting `sync-rsync.compareDown not found` when trying to use this plugin. 

Any tips would be helpful

**Comment by thisboyiscrazy** [comment]
Usually means the plugins not loaded. Double check in your settings that
you have some settings related to the plugin

**Comment by thisboyiscrazy** [comment]
@charlesbodman did you resolve this?

**Comment by thisboyiscrazy** [comment]
When you open visual studio code, in the output windows (Crtl+k Ctrl+H)  what does it say when you select "Sync-Rsync"?

**Comment by charlesbodman** [comment]
I don't think I did get it to work. I'll try again soon. 
Ended up just making a tool. https://github.com/charlesbodman/remotely

**Comment by thisboyiscrazy** [comment]
Closing because of no response
