### ISSUE TITLE
OSx

### ISSUE THREAD

**Issue by antrianis** [thisboyiscrazy/vscode-rsync#22]
It doesn't work on mac.
I get not found for all commands after installing.
command 'sync-rsync.compareDown' not found

Is there anything else to configure?

**Comment by thisboyiscrazy** [comment]
Did you configure the Local and Remote in the workspace settings?

**Comment by antrianis** [comment]
Yes, in this way:
    "sync-rsync.remote": "user@server:/path/",
    "sync-rsync.local": "${workspaceRoot}/"
Is it correct?

**Comment by thisboyiscrazy** [comment]
Seems related to #21 

Try this just this in your workspace settings

```
{
    "sync-rsync.remote":"user@server:/path/"
}
```

"sync-rsync.local defaults to workspace root.

**Comment by antrianis** [comment]
Tried. Same result.

**Comment by thisboyiscrazy** [comment]
Email me an email at thisboyiscrazy@gmail.com and we'll see if we can get
this fixed.

**Comment by thisboyiscrazy** [comment]
@antrianis Is this still not working? can you email me if not I not not have access to OSx to test.

**Comment by thisboyiscrazy** [comment]
When you open visual studio code, in the output windows (Crtl+k Ctrl+H)  what does it say when you select "Sync-Rsync"

**Comment by arvindr01** [comment]
I have the same issue in osx. Additionally I am trying to rsync to a non-standard port. Below is the settings file values
`{
    "sync-rsync.shell": "ssh -p 9022",
    "sync-rsync.remote": "root@dockermc:/var/www/html/"
}`

Below is the output that I get.

`> rsync -rlptzv --progress --rsh="ssh -p 9022" --exclude=.git --exclude=.vscode root@dockermc:/var/www/html/ /<local_folder_to_sync>/
rsync: Failed to exec ssh -p 9022: No such file or directory (2)
rsync error: error in IPC code (code 14) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-51/rsync/pipe.c(86) [receiver=2.6.9]
rsync: connection unexpectedly closed (0 bytes received so far) [receiver]
rsync error: error in IPC code (code 14) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-51/rsync/io.c(453) [receiver=2.6.9]`

When I execute the rsync command in a terminal then it works fine. 
`rsync -rlptzv --progress --rsh="ssh -p 9022" --exclude=.git --exclude=.vscode root@dockermc:/var/www/html/ /<local_folder_to_sync>/`

**Comment by thisboyiscrazy** [comment]
Closing because of no response
