### ISSUE TITLE
How to use certificate for connection

### ISSUE THREAD

**Issue by androlets** [thisboyiscrazy/vscode-rsync#23]
Hi. I need to use certificate for ssh connection. Where and how it could be configured?

**Comment by thisboyiscrazy** [comment]
A certificate or a key?

**Comment by iryston** [comment]
Hello! How to use a key for ssh connection?

**Comment by thisboyiscrazy** [comment]
If you are using linux, macso, or cygwin on window ssh will handle that for you.

If you need to specifiy a key you can use:
```
"sync-rsync.shell": "ssh -I ~/.ssh/id_dsa"
```

**Comment by BigRedT** [comment]
Hi, 

I am trying to sync a remote folder to my local machine as well and was trying to specify the ssh key as well. This solution didn't work for me.

**Settings**
```
"sync-rsync.local": "/Users/tanmay/Code/vision-server3/rsync_test/",
"sync-rsync.remote": "tanmayg@vision-server3:/home/tanmayg/Code/vision-animation-gan/",
"sync-rsync.shell": "ssh -i /Users/tanmay/.ssh/tanmay_mac_key",
"sync-rsync.executableShell": "/bin/bash",
```

**OS** 
I am using macOS on the local and the remote is running Linux. 

**Error Log**
This is what I see when I run `Sync-Rsync: Sync Remote to Local`:
```
> rsync -rlptzv --progress --rsh="ssh -i /Users/tanmay/.ssh/tanmay_mac_key" --exclude=.git --exclude=.vscode tanmayg@vision-server3:/home/tanmayg/Code/vision-animation-gan/ /Users/tanmay/Code/vision-server3/rsync_test/ 
rsync: Failed to exec ssh -i /Users/tanmay/.ssh/tanmay_mac_key: No such file or directory (2)
rsync error: error in IPC code (code 14) at pipe.c(85) [Receiver=3.1.3]
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [Receiver=3.1.3]
```

However, if I take that first line in the error log and run it in the terminal separately, it works.

**Comment by thisboyiscrazy** [comment]
Try the solution in the issue.

https://github.com/thisboyiscrazy/vscode-rsync/issues/35

**Comment by reyder** [comment]
Define special name here: ~/.ssh/config

example:

`    IdentityFile ~/.ssh/id_ed25519
Host example_host
    User reyder
    Port 4544
    HostName 6.6.6.6
    IdentityFile ~/.ssh/id_ed25519`

after that you cane use it like this:

"remotePath":"reyder@example_host:/home/reyder/www/",

Setting this doesn't work for me on macOS.
 "sync-rsync.executableShell": "/bin/bash"

**Comment by BigRedT** [comment]
@reyder's solution worked for me. Did not try #35
