### ISSUE TITLE
Rsync error on non-standard port

### ISSUE THREAD

**Issue by arvindr01** [thisboyiscrazy/vscode-rsync#24]
I am on osx 10.12.6 and i get rsync error 14 when I try to sync to a server which is on non-standard port. Below is the settings file values
`{
    "sync-rsync.shell": "ssh -p 9022",
    "sync-rsync.remote": "root@dockermc:/var/www/html/"
}`

Below is the output that I get.

`> rsync -rlptzv --progress --rsh="ssh -p 9022" --exclude=.git --exclude=.vscode root@dockermc:/var/www/html/ /<local_folder_to_sync>/
rsync: Failed to exec ssh -p 9022: No such file or directory (2)
rsync error: error in IPC code (code 14) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-51/rsync/pipe.c(86) [receiver=2.6.9]
rsync: connection unexpectedly closed (0 bytes received so far) [receiver]
rsync error: error in IPC code (code 14) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-51/rsync/io.c(453) [receiver=2.6.9]`

When I execute the same rsync command in a terminal then it works fine. 
`rsync -rlptzv --progress --rsh="ssh -p 9022" --exclude=.git --exclude=.vscode root@dockermc:/var/www/html/ /<local_folder_to_sync>/`

The rsync works fine when I try to sync to a remote server that is on standard port (22).

**Comment by thisboyiscrazy** [comment]
OK I see where I think the bug is I will try and get it fixed soon.
```
rsync -rlptzv --progress -e "ssh -p 9022" --exclude=.git --exclude=.vscode root@dockermc:/var/www/html/ /<local_folder_to_sync>/
```
in terminal and see if it works?

**Comment by arvindr01** [comment]
Thanks. This works fine too in the terminal.

`rsync -rlptzv --progress -e "ssh -p 9022" --exclude=.git --exclude=.vscode root@dockermc:/var/www/html/ /<local_folder_to_sync>/`

**Comment by thisboyiscrazy** [comment]
What I though was the problem was not. I do not have a access to a mac to develop on. I am going to see if I can find a Mac MV somewhere I can use. If not would you be will to do a remote session?

**Comment by xsbear** [comment]
I have the same issue in Mac, It works fine in the terminal

**Comment by thisboyiscrazy** [comment]
try adding this

```
"sync-rsync.executableShell":  "/bin/bash"
```

**Comment by arvindr01** [comment]
I confirm that adding the sync-rsync.executableShell parameter that you specified along with the others ("sync-rsync.shell": "ssh -p 9022") works. 

`"sync-rsync.executableShell":  "/bin/bash"`

Thanks for resolving this quickly. I will close this issue.

**Comment by javsalgar** [comment]
I am having the same issue in Ubuntu 17.10. Adding the options that @arvindr01 mentioned do not work.

```
    "sync-rsync.executableShell": "/bin/bash",
    "sync-rsync.shell": "ssh -p 22009"
```

```
> rsync -rlptzv --progress --rsh="ssh -p 22009" --exclude=.vscode  --exclude=.git FOLDER HOST 
rsync: Failed to exec ssh -p 22009: No such file or directory (2)
rsync error: error in IPC code (code 14) at pipe.c(85) [sender=3.1.2]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(235) [sender=3.1.2]
```

**Comment by ianlini** [comment]
I can confirm that this works on ubuntu 18.04 with rsync 3.1.2:
```
    "sync-rsync.executableShell": "/bin/bash",
    "sync-rsync.shell": "ssh -p 12345"
```
