### ISSUE TITLE
More control on when to run rsync

### ISSUE THREAD

**Issue by ifish12** [thisboyiscrazy/vscode-rsync#25]
Hello,

I love this extension you've made, currently each time you update I edit the plugin's extension.js file (which I still find weird that it's extension.ts in this repository, I'm really new to the world of VS Code plugins) to add this like of code 
```
vscode_1.workspace.onDidOpenTextDocument(() => {
           debouncedSyncUp(config);
    });
```

The reason I do this is because I use your plugin as an alternative to mounting a remote volume with sshfs which is way too slow for Git's VS Code integration. Currently the only way to get our remote to switch branches is forcing a save (usually making a space and saving), this code makes it so each time we open a file it syncs. This isn't ideal, but at the moment it works. 

I'm open to idea, maybe a button on the status bar. I'm super new to the world of VS Code, so I haven't really made my own version of your extension to test / submit a pull request yet. I've just been re-editing the file each time you update. 

Thanks!

**Comment by thisboyiscrazy** [comment]
Yeah the reason I made it was because mount ssh was to slow.

I currently have sync on save so when you save a file it syncs the local to remote.

Are you asking for when you open a file sync remote to local?

**Comment by ifish12** [comment]
Yeah, that's what I was suggesting but in the opposite direction, I'm open to other ideas if you think you have a better and more efficient way to manually trigger a file sync. 

Not from remote to local, but from local to remote. The same type of sync that happens when you sync a file (ctrl/cmd+s). I'd love this because when we switch branches through VS Code, but not necessarily make any file changes we'd like our web server to change branch as well. 

Currently to do this(without modifying the tool) we change branches(In VS Code), add a space to a file, and save it so it our dev server is on the right branch. 

With my change, when we open a file, it does the same behaviour as saving.

**Comment by thisboyiscrazy** [comment]
I will have to think about this. Seems like there might be a better way.

**Comment by ifish12** [comment]
I agree 100%, I think this suggested method is pretty bad, but it was a quick dirty hack to get my dev team back up and running. 

I was looking into a way to watch in VS Code whether you switch branches with the UI, but I couldn't find a way to capture that trigger. Because that's really the ideal way in my mind

**Comment by thisboyiscrazy** [comment]
You can put something like this in your keybindings:

```
[
    { "key": "ctrl+u",         "command": "sync-rsync.syncUp"}
]
```

you don't have to have a file open to sync, just a folder.

**Comment by ifish12** [comment]
Hey thanks! This is perfect for us. I feel silly for not knowing I could do this ^^;
