### ISSUE TITLE
per workspace configuration files

### ISSUE THREAD

**Issue by CarloLucibello** [thisboyiscrazy/vscode-rsync#26]
Maybe I am not using this extension as it should be used, but I'm having troubles in configuring it in such a way that I can sync independently all my projects. I would like to have something like this
```   
 "sync-rsync.onSave": true,

# Proj1 settings 
 "localPath":"Proj1/" 
"remotePath":"me@myhost:~/work/Proj1/"

# Proj2 settings 
 "localPath":"Proj2/"
"remotePath":"me@myhost:~/work/Proj2/"
```
and have rsync syncrhonize only the folder Proj1 when I'm working there. Is that possible?

**Comment by thisboyiscrazy** [comment]
In visual studio code, when you go to preferences -> setting. Make sure you are putting the settings in the "Workspace Settings". It sounds like you are putting them in "User Settings". The selection is on the upper right when viewing settings to the right of "Search Settings".

**Comment by CarloLucibello** [comment]
Ah, right. Sorry for the noise, still new to vscode. thanks!
