### ISSUE TITLE
extension can't execute properly

### ISSUE THREAD

**Issue by shtse8** [thisboyiscrazy/vscode-rsync#27]
I have installed rsync and cygwin properly and i have tried this command and it works fine.
but i don't understand why the extension got no following output after executing the command .

```

Sat Nov 11 2017 20:51:16 GMT+0800 (中国标准时间) syncing
> rsync -rlptzv --progress --delete --exclude=.vscode /cygdrive/c/Users/shtse/CMPool/ root@35.199.189.36:/var/workspace/CMPool/

Sat Nov 11 2017 20:51:28 GMT+0800 (中国标准时间) syncing
> rsync -rlptzv --progress --delete --exclude=.vscode /cygdrive/c/Users/shtse/CMPool/ root@35.199.189.36:/var/workspace/CMPool/

```

**Comment by shtse8** [comment]
I know the reason now. it can't support cygwin shell at the moment. so i have created a bat for making it works

**Comment by thisboyiscrazy** [comment]
It does work with cwRsync and delta copy.

**Comment by shtse8** [comment]
@thisboyiscrazy The main problem is that, nodejs `createChild()` will auto append `/d /s /c` on Windows. but for cygwin shell, it only support `-c`. This is the current bat I am using for making it works on cygwin for translating the command to cygwin compatible. 
```
@echo off
echo INPUT: %4
for /f "tokens=3,* delims= " %%a in ("%*") do set CMD=%%b
SET CMD=%CMD:~1,-1%
REM SET CMD=%CMD:"=^"%
echo COMMAND: %CMD%
C:\\cygwin64\\bin\\bash.exe -l -c "%CMD%"
```
