### ISSUE TITLE
Saving User Settings shouldn't rsync project

### ISSUE THREAD

**Issue by jimbonator** [thisboyiscrazy/vscode-rsync#30]
Whenever I save my User Settings file, the current workspace project is synchronized with the server.  I would expect only files in the workspace itself to trigger an rsync.

**Comment by thisboyiscrazy** [comment]
Yeah it triggers on any file save. I will try and fix that next week.

**Comment by thisboyiscrazy** [comment]
There is no way around this but 57c73b77edbc059fdc17d839ee710e3c6a518f6a helps because when it tries to sync the individual file it will ignore it.
