### ISSUE TITLE
Can't set local 

### ISSUE THREAD

**Issue by jas99** [thisboyiscrazy/vscode-rsync#31]
I tired extension with multiproject workspace; the first project of the workspace gets synced, no matter whats the local directory is set.

Does this extension support multiproject workspace?

**Comment by thisboyiscrazy** [comment]
Put this in you workspace settings file

```
"settings": {
	"sync-rsync.sites": [
		{
			"localPath": "/home/user/project/s1",
			"remotePath": "user@server:/var/www/s1"
		},
		{
			"localPath": "/home/joe/projects/t2",
			"remotePath": "user@server:/var/www/s2"
		}
	]
}
```

**Comment by jas99** [comment]
The reason of opening this issue was that the above setting was not working, although I tried again and it does.
