### ISSUE TITLE
Cygwin Remote ssh connection

### ISSUE THREAD

**Issue by bajoodoo** [thisboyiscrazy/vscode-rsync#32]
When syncing to a network drive, it works using "//1.2.3.4/folder" but if I want to rsync remotely using ssh, ie. "user@1.2.3.4:/folder", there is still an error:

rsync: Failed to exec ssh: No such file or directory (2)
rsync error: error in IPC code (code 14) at pipe.c(85) [sender=3.1.2]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]

**Comment by lRawd** [comment]
I had a similar error when SSH was not in my PATH

**Comment by thisboyiscrazy** [comment]
set `"sync-rsync.shell": "C:\\cygwin64\\bin\\ssh.exe"`

**Comment by bajoodoo** [comment]
sounds good, did that and it works.
only one question: could you tell me how to implement ssh args (-i for pubkey auth for example)? if I do directly after ssh.exe, I'll get a "file not found" but when I copy the command string to cygwin itself, it works there...

**Comment by bajoodoo** [comment]
Have you tried shell options on windows? like -p 123 or -i /path/to/key? I do not get this working, as soon as I add an option to the ssh command, I'll get:

rsync: Failed to exec W:\Cygwin\bin\ssh.exe -I W:\_private\id_rsa: No such file or directory (2)
rsync error: error in IPC code (code 14) at pipe.c(85) [sender=3.1.2]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]
