### ISSUE TITLE
ssh params won't work in windows

### ISSUE THREAD

**Issue by bajoodoo** [thisboyiscrazy/vscode-rsync#35]
Have you tried shell options on windows? like Port (-p 123) or Key (-i /path/to/key)? I do not get this working, as soon as I add an option to the ssh command, I'll get (for example):

rsync: Failed to exec W:\Cygwin\bin\ssh.exe -i W:\private\id_rsa: No such file or directory (2)
rsync error: error in IPC code (code 14) at pipe.c(85) [sender=3.1.2]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]

Thank you for this great extension :)

**Comment by discovery01** [comment]
I'm getting the exact same error.

Running the standalone command in the Cygwin terminal works as expected.

**Comment by philipsoeberg** [comment]
I fought this too. In the interim you can use a simple wrapper:

In cygwin, make file /bin/ssh_wrap.sh
```
#!/bin/bash
/bin/ssh -i ~/my.sshkey.priv $@
```

and in vscode settings.sh, set
`sync-rsync.shell": "/bin/ssh_wrap.sh`

simple and working..

**Comment by bajoodoo** [comment]
great idea @philipsoeberg :)

**Comment by thisboyiscrazy** [comment]
I am looking into it, I can not find a fix yet. In the mean time you will have to use the sccript @philipsoeberg recommended.

**Comment by thisboyiscrazy** [comment]
I updated the documentation thanks @philipsoeberg

**Comment by thisboyiscrazy** [comment]
Should should work without the extra file in 0.25.0
