### ISSUE TITLE
command 'sync-rsync.compareUp' not found

### ISSUE THREAD

**Issue by silverl** [thisboyiscrazy/vscode-rsync#39]
Just installed. VS Code 1.20.1.

Set up user config as documented.

Upon attempting my first rsync, I'm getting this error bar at the top of VS Code:

`ERROR: command 'sync-rsync.compareUp' not found`

Same thing with compareDown.

I've tried uninstalling and re-installing the plugin.

I'm a decade-old user of Cygwin, and I'm pretty sure I've got that part right.

**Comment by thisboyiscrazy** [comment]
Usually that means there is something wrong with the config. Do mind posting it?

**Comment by silverl** [comment]
I seem to have gotten past the issue. I'm trying to find the best SSH client on Windows, and they all seem to have issues. Let's close this one.

**Comment by silverl** [comment]
I stopped using it and have since removed the config from my settings. Sorry!
