### ISSUE TITLE
Add global default for 'exclude' and 'shell'.

### ISSUE THREAD

**Issue by artiswilliams** [thisboyiscrazy/vscode-rsync#40]
It would be nice to have a global default config for exclude and shell instead of needing to set it on each synced folder.

I have dozens of sites built on the same CMS/Framework that have the same lists of exclude files, but I have to duplicate those config for each site.

**Comment by thisboyiscrazy** [comment]
It does

```
"sync-rsync.exclude"
```

and 

```
"sync-rsync.shell"
```

**Comment by thisboyiscrazy** [comment]
Does
```
"sync-rsync.exclude"
```
and
```
"sync-rsync.shell"
```

not work? or not do what you are looking for?

**Comment by artiswilliams** [comment]
Well, you know, I never tried them.  
I used 'exclude' and 'shell' in 
`sync-rsync.sites`
But there wasn't any documentation about using those keys as default globals so I assumed they wouldn't work.  
My bad.

**Comment by thisboyiscrazy** [comment]
I will look into fixing the documentation
