### ISSUE TITLE
Integrate with Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by fermuso** [thisboyiscrazy/vscode-rsync#43]
Hi.
I try to integrate vscode-rsync with bash on Windows Subsystem for Linux (Ubuntu distro) without Cygwin:
_DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"_

My vscode-rsync configuration:
**"sync-rsync.executableShell": "C:\\WINDOWS\\System32\\bash.exe",
"sync-rsync.executable": "/usr/bin/rsync",
"sync-rsync.shell": "/usr/bin/ssh",
"sync-rsync.local": "/mnt/c/Users/<MY_USER>/Documents/<MY_PROJECT>",**

The error output:
> /usr/bin/rsync -rlptzv --progress --rsh=/usr/bin/ssh --delete --exclude=.git --exclude=.gitignore --exclude=.vscode /mnt/c/Users/<MY_USER>/Documents/<MY_PROJECT> remote_user@remote_server:/path/to/remote/ 
**ERROR > spawn /usr/bin/rsync ENOENT**

I also try this conf:
"sync-rsync.executable": "bash.exe -c /usr/bin/rsync",

Fail output:
> bash.exe -c /usr/bin/rsync -rlptzv --progress --rsh=/usr/bin/ssh --delete --exclude=.git --exclude=.gitignore --exclude=.vscode /mnt/c/Users/<MY_USER>/Documents/<MY_PROJECT> remote_user@remote_server:/path/to/remote/ 
**ERROR > spawn bash.exe -c /usr/bin/rsync ENOENT**

Is posible this integration?, how?

**Comment by idanpa** [comment]
Managed to get this working with #44 and "sync-rsync.executableShell": "bash".

**Comment by nbourre** [comment]
So what was the solution? I've followed #44, but did not understood.

**Comment by idanpa** [comment]
@nbourre, I use something like this:

```
"sync-rsync.onSave": true,
"sync-rsync.executable": "rsync",
"sync-rsync.executableShell": "bash",
"sync-rsync.remote": "remote_hostname:/home/idanp/my_code/",
"sync-rsync.local": "/mnt/c/Users/idanp/my_code/",
"sync-rsync.flags": "avhP",
```
