### ISSUE TITLE
Error on sync: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by evannoronha** [thisboyiscrazy/vscode-rsync#45]
![image](https://user-images.githubusercontent.com/6803522/38753405-1b811efe-3f13-11e8-95fd-14823e0a7df5.png)

![image](https://user-images.githubusercontent.com/6803522/38753408-1f961d46-3f13-11e8-8dae-bfaebd9990b7.png)

config:
```
{
    "folders": [
        {
            "path": "/Users/Evan/path/to/empty/folder"
        }
    ],
    "settings": {
        "sync-rsync.remote": "user@host.com:Code/",
        "sync-rsync.autoShowOutput": false,
        "sync-rsync.delete": true,
        "sync-rsync.onSaveIndividual": true,
        "files.autoSave": "afterDelay",
        "files.autoSaveDelay": 667,
        "sync-rsync.exclude": [
[ REDACTED ]
       ],
      "diffEditor.ignoreTrimWhitespace": false,
      "php.suggest.basic": false,
      "phpcs.standard": "./phpcs.xml",
   },
   "extensions": {
      "recommendations": [
         "vscodevim.vim",
         "eamodio.gitlens",
         "vsmobile.vscode-react-native",
         "ikappas.phpcs",
         "HvyIndustries.crane",
         "felixfbecker.php-intellisense"
      ]
   }
}

```

I successfully ran this config on another machine and the sync worked. I'm using:
![image](https://user-images.githubusercontent.com/6803522/38753570-a601c970-3f13-11e8-886f-c53a9eab2f2b.png)

**Comment by thisboyiscrazy** [comment]
Is this still happening?

I tested in High Sierra with you settings

```
{
	"folders": [
		{
			"path": "/Users/joe/projects/test"
		}
	],
	"settings": {
		"sync-rsync.remote": "user@server:~/folder",
		"sync-rsync.autoShowOutput": false,
		"sync-rsync.delete": true,
		"sync-rsync.onSaveIndividual": true,
		"files.autoSave": "afterDelay",
		"files.autoSaveDelay": 667,
		"sync-rsync.exclude":[
			".git",
			".vscode"
		],
		"diffEditor.ignoreTrimWhitespace": false,
  		"php.suggest.basic": false,
  		"phpcs.standard": "./phpcs.xml",
	},
	"extensions": {
  		"recommendations": [
			"vscodevim.vim",
			"eamodio.gitlens",
			"vsmobile.vscode-react-native",
			"ikappas.phpcs",
			"HvyIndustries.crane",
			"felixfbecker.php-intellisense"
		]
	}
}
````

And had no problem.

**Comment by evannoronha** [comment]
Yeah, unfortunately. I've gone so far as to remove VSCode and rsync and reinstall both of them and I still get the same issue. I'm chugging along pretty happily in vim though, so this is pretty low priority for me.

**Comment by thisboyiscrazy** [comment]
If I had any guess at all it is that it has some to do with a version of nodejs installed on your mac. The name 'value' only show up on a __await function used by the transpiler. Sense i can not seem to replicate it would you like to help me debug it? Otherwise I will close the issue.

**Comment by evannoronha** [comment]
Meh. I'm pretty happy with my setup. I'll reopen this if I have time to look into it in the future.

Thank you!
