### ISSUE TITLE
this not work on win

### ISSUE THREAD

**Issue by SquirrelMajik** [thisboyiscrazy/vscode-rsync#5]
``` javascript
let r = new rsync();
r.cwd(local);
if(down) {
  r = r.source(remote).destination('.');
} else {
  r = r.source('.').destination(remote);
}
```
This should be better. Could I join?

**Comment by thisboyiscrazy** [comment]
Join?

Someone else seems to be using it on windows See issue #2 

What seems to be the problem with it now working? I think rsync for windows uses cygwin which does paths differently than windows.

**Comment by SquirrelMajik** [comment]
I work with pure cmder.

Due to path '\' in win and '/' in unix like, it makes a mess.
My workspace on win like `C:\User\xxx\Code\`.
Remote address on linux like `/home/xxx/Code/`.

With the origin code, it will sync `\User\xxx\Code\` to `/home/xxx/Code/\User\xxx\Code\`.
So I set the cwd with local, it will sync `.` to `/home/xxx/Code/./` within cwd `\User\xxx\Code\`.
This works well in cygwin.

I want to push some code.

**Comment by thisboyiscrazy** [comment]
You are always welcome to create pull request.

I just push out a change that may have been causing the problem. I was appending a '/' to both local and remote paths. This is an issues in windows because it uses '\'. I changed it to path.delimiter.

Let me know if that fixes it.

**Comment by SquirrelMajik** [comment]
sorry, that's not the problem.
`node-rsync` only support cygwin and I don't want it.
In my code, it works on cmd or powershell with rsync.exe

**Comment by thisboyiscrazy** [comment]
I want to do a little testing. This seems like it should be considered a issue with ```node-rsync``` the rsync you are using is non cygwin, where can I get it so I can test somethings?

**Comment by SquirrelMajik** [comment]
`rsync.exe` is the same as  the one in cygwin.
U can also get it here. [rsync.exe](https://www.itefix.net/cwrsync)
Then run it with cmder rather than cygwin.

**Comment by thisboyiscrazy** [comment]
I tried the rsync from the you posted. Because it does use cywgin you will need to set local using cygdrive

```
"sync-rsync.local": "/cygdrive/c/Users/joe/Documents/projects/sync_test/"
```

Then is worked for me.
