### ISSUE TITLE
Auto sync file from remote on open.

### ISSUE THREAD

**Issue by artiswilliams** [thisboyiscrazy/vscode-rsync#50]
It would be nice to have a site/global setting for downloading a file from the remote whenever it is opened.  This would reduce the chances of a remote file being overwritten by an older version of the file when working form two different systems.

For example, I'm working on a project that lives on a remote server.  I do some coding from home and some from the office.  When going back and forth I have to be sure to "Sync From Remote" on each system before coding.  If I forget and work on the same file consecutively from each system then I'll invariably upload a version of the file that is out of date.

**Comment by thisboyiscrazy** [comment]
Hopefully, I will get some time to work on this Monday. rsync does have a ```-u``` argument that will not override newer files on the destination. Will that work for you?

**Comment by momiji** [comment]
Hi, done in last #62. Hope it is what you were looking for...

**Comment by artiswilliams** [comment]
This should work but when I add "sync-rsync.autoLoadIndividual": true to my workspace settings VSCode complains that it is unknown configuration setting.

Thoughts?

**Comment by thisboyiscrazy** [comment]
@artiswilliams I believe it is `sync-rsync.onLoadIndividual`
