### ISSUE TITLE
Rsync Fails over SSH in case there is a passphrase added to rsa-id

### ISSUE THREAD

**Issue by gauravchaddha** [thisboyiscrazy/vscode-rsync#52]
Rsync plugin does not sync over SSH in case the passphrase for rsa-id is non empty.

Following is the failure message. The same command generated by plugin is working ok in the Cygwin terminal. I also tried adding a ssh-agent. In this case passphrase is not required by the cygwin terminal and should supposedly work on the plugin as well. 

Issues details - 
Permission denied (publickey).
ssh_exchange_identification: Connection closed by remote host
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]

Please check and let me know if there is a known workaround for this. 

Regards,
Gaurav

**Comment by thisboyiscrazy** [comment]
I have not had any ask about using the extension with a key with a passphrase. I will look into it.

Are you mainly using Windows with Cygwin, Windows with WSL. Linux, or Mac OS?

**Comment by gauravchaddha** [comment]
Thanks. I am using Windows with Cygwin. Looking forward for the update.

**Comment by thisboyiscrazy** [comment]
The trick is to launch vscode from cygwin terminal so it has the env vars.

Here is what I got to work:

In cygwin terminal:
```
$ eval `ssh-agent -s`  #start ssh-agent
$ ssh-add              #add password
$ code                 #start vscode
```

My workspace settings looks like this:

```
{
    "sync-rsync.remote": "user@server:/home/user/test/",
    "sync-rsync.local": "C:\\Users\\user1\\Documents\\test",
    "sync-rsync.executableShell": "C:\\cygwin64\\bin\\\\bash.exe",
    "sync-rsync.executable": "/bin/rsync",
    "sync-rsync.shell": "/bin/ssh",
    "sync-rsync.cygpath": "C:\\cygwin64\\bin\\cygpath.exe"
}
```

Let me know if that works for you.

**Comment by gauravchaddha** [comment]
Thanks a lot, this works for me :)
