### ISSUE TITLE
support include settings

### ISSUE THREAD

**Issue by lazyc97** [thisboyiscrazy/vscode-rsync#53]
I'm using java vscode extension and it generate lots of files which I don't want to sync, I only want to sync certain file extensions like `*.java` and `*.sh`. Therefore I want to set exclude to `*` and include what I want.

Current behavior: Using `sync-rsync.options` only the first include will be used.
What I want: `sync-rsync.include` which work just the opposite of `sync-rsync.exclude`.

**Comment by thisboyiscrazy** [comment]
Should be added in bb9cb3cebb7569d3b9a44fbd07d4b0694d7e4556
