### ISSUE TITLE
Permission denied when passing through a proxy

### ISSUE THREAD

**Issue by netw0rkf10w** [thisboyiscrazy/vscode-rsync#54]
Hello,

First of all thank you so much for the great plugin!

When using it to sync with a remote server through a proxy, I got some permission denied errors.

Suppose that my remote server is `123.456.789.0` (access with username and password) and my proxy server is `user@proxy.server` (access with public SSH key). I created a file `~/.ssh/config ` with the following content:

```
Host 123.456.789.0
    ProxyCommand ssh -W %h:%p username@proxy.server 123.456.789.0
```

Now in the terminal I can do `ssh username@123.456.789.0` without any problem, but when setting the plugin in VS Code:

```
    "sync-rsync.onSaveIndividual": true,
    "sync-rsync.sites": [
        {
            "localPath": "/Users/somepath/",
            "remotePath": "username@@123.456.789.0:/home/somepath/"
        }
    ]
```
it's not working (permission denied).

My remote server is running Ubuntu and my local machine is on Mac OS High Sierra.

Thank you in advance for your help!

**Comment by thisboyiscrazy** [comment]
Can you post the output from Sync-Rsync from the output window? Looks like
you are ssh to proxy into another network?

**Comment by netw0rkf10w** [comment]
@thisboyiscrazy To make it clear let me explain again.

In the above example, the final remote server that I want to access is `123.456.789.0`. For this, I have to ssh to another machine `proxy.server` with username `username`, and from this machine ssh to `123.456.789.0`. In summary, I would need to type two following consecutive commands in my Mac terminal to access `123.456.789.0`:

```
ssh username@proxy.server
ssh username@123.456.789.0
```
The first one does not ask for my password because it's using my public ssh key, but the second one does.

Instead of typing two commands every time, I created a file `~/.ssh/config` with the following content:
```
Host 123.456.789.0
    ProxyCommand ssh -W %h:%p username@proxy.server 123.456.789.0
```
Now in the terminal I only need to type
```
ssh username@123.456.789.0
```

I guess the `rsync` plugin does not take into account the content of `~/.ssh/config`.

**Comment by netw0rkf10w** [comment]
@thisboyiscrazy I replaced the password authentication by SSH public key and it works now.
Your plugin is really great! I have been using it for some time, and when I encountered the above proxy/password problem I thought maybe I should look for an alternative plugin. But now I'm very happy that I can continue to use it. Thanks a lot!

**Comment by thisboyiscrazy** [comment]
Ok that's. Just FYI the plug-in does not work if you have to enter a
password. There is no way to input it. But I will see if I can add that.

**Comment by netw0rkf10w** [comment]
Yes, I think allowing password authentication would be a nice feature!

**Comment by thisboyiscrazy** [comment]
It looks like I cannot do user input well so I am closing this.
