### ISSUE TITLE
VSCode extension rsync cannot find module lodash.debounce 

### ISSUE THREAD

**Issue by ashmeet95** [thisboyiscrazy/vscode-rsync#55]
Hello,
I have installed the extension but its not working. By referring to one of the previously logged issues I launched the vscode in verbose mode and found that it is providing below error.

'vscode-ext.sync-rsync' failed: Cannot find module 'lodash.debounce'

Please advise.

**Comment by thisboyiscrazy** [comment]
That's interesting lodash is a dependent and should get installed when you install the plugin. Try uninstalling and reinstalling the plugin. Let me know if that doesn't work.

**Comment by ashmeet95** [comment]
I have tried uninstalling and reinstalling the plugin.It is still not working
Please advise .

**Comment by thisboyiscrazy** [comment]
Ok I am going to try a frsh install and see if it pulls in lodash. I will
let you know. Thanks for the patience.

**Comment by ashmeet95** [comment]
ok...will definitely wait for your reply.

**Comment by thisboyiscrazy** [comment]
ok, I just tried it in Linux, MAC, and Windows and it seemed to work. Can you remove the extension, start vscode in verbose mode, install the extension and look for any errors?

Or try:

```bash
cd ~/.vscode/extensions/vscode-ext.sync-rsync-0.25.2
npm i
```

This should install lodash.

**Comment by thisboyiscrazy** [comment]
@ashmeet95 does it still not work for you?

**Comment by ashmeet95** [comment]
Thanks for your kind help and concern @thisboyiscrazy ...
It is working now.
Tried uninstalling and installing again at different location and setting the path in environment variables and it started working.
