### ISSUE TITLE
Addon keep changing OUTPUT tab to rsync

### ISSUE THREAD

**Issue by wsielskx** [thisboyiscrazy/vscode-rsync#56]
Every time the RSYNC run it changes the OUTPUT to RSYNC logs. How can I prevent such behaviour? For me, it's more than enough to watch the icon status at the bottom bar.

**Comment by thisboyiscrazy** [comment]
I will look into disabling that.

**Comment by thisboyiscrazy** [comment]
Try setting:

```
sync-rsync.autoShowOutput
```

to false

**Comment by wsielskx** [comment]
Doesn't work for me. 

> "sync-rsync.autoHideOutput": true,
> "sync-rsync.autoShowOutput": false

Keep changing Jest tab to rsync.

**Comment by thisboyiscrazy** [comment]
@wsielskx I cannot seem to replicate this / or need more info.

The only way it should show the output is if you either have
```
"sync-rsync.autoShowOutput": false
```
which should be the default.

or if you click the "Rsync" in the status bar.

Can you give more info on your env. OS / Version of vscode / Version on Sync-Rsync plugin?

**Comment by wsielskx** [comment]
> {
>     "sync-rsync.delete": true,
>     "sync-rsync.flags": "avu",
>     "sync-rsync.onSaveIndividual": true,
>     "sync-rsync.exclude": [
>         ".git",
>         ".vscode",
>         "node-modules"
>     ],
>     "sync-rsync.sites": [
>         {
>             "localPath":"XXX",
>             "remotePath":"YYY",
>         }
>     ],
>     "sync-rsync.autoHideOutput": true,
>     "sync-rsync.autoShowOutput": false
> }

I can see what's the problem. Rsync toggles to its output always if it fails. Sorry about that. Still, can we prevent such behaviour even when rsync fails?

**Comment by wsielskx** [comment]
<3 great job!
