### ISSUE TITLE
Feature request: automatically add trailing slash to local/remote

### ISSUE THREAD

**Issue by jacobweber** [thisboyiscrazy/vscode-rsync#61]
The `localPath` and `remotePath` settings need a trailing slash at the end. I've messed things up in the past by forgetting those. It would be nice if the plugin automatically added them, even if you left them off, just to be safe.

**Comment by thisboyiscrazy** [comment]
The question is on the remote side. On the local side, I can use path.sep on the remote side there is no way to know if it is "/" or "\" for example.

Any ideas? is it safe to assume "/"?

**Comment by jacobweber** [comment]
On the remote side, I think it's always a "/". Otherwise you'd need to know the remote server's platform before using rsync. The UNIX rsync man page only refers to "/" characters.

Actually I'm pretty sure rsync always uses "/", on the local side as well. I wrote a similar plugin for Eclipse a while back, and forward slashes worked fine on Windows clients, for the local paths. This was using "cwRsync" with cygwin; I haven't tried other clients.
