### ISSUE TITLE
cygpath on Windows does not exist

### ISSUE THREAD

**Issue by lopsd07** [thisboyiscrazy/vscode-rsync#67]
In the version 0.33.0 [commit](https://github.com/thisboyiscrazy/vscode-rsync/commit/c2a422fc3bdb3e8b8a41390d09cae2f454a90a80#diff-45327f86d4438556066de133327f4ca2R101), the local path check for cygpath, for example  `/cygdrive/e/Code/` does not work.

**Comment by thisboyiscrazy** [comment]
Can you post a copy of the relevant part of your setting?

I made some changes that may have effected cygwin.

**Comment by thisboyiscrazy** [comment]
Also, try 0.34.0 it may have fixed it.

**Comment by thisboyiscrazy** [comment]
I just pushed 0.34.1 that I think fixes the issue. Try it and close if it is fixed.

**Comment by lopsd07** [comment]
It is fixed. Thanks!
