### ISSUE TITLE
doesn't work anymore on windows

### ISSUE THREAD

**Issue by momiji** [thisboyiscrazy/vscode-rsync#70]
Please see my comment on the problematic commit https://github.com/thisboyiscrazy/vscode-rsync/commit/82c2ad7fa32f72fd10885333b776fe16224b571e#r32205145.

Meanwhile, I just added missing -c like this:
```
"sync-rsync.executableShell": "d:\\cygwin64\\bin\\bash.exe -c",
```

**Comment by thisboyiscrazy** [comment]
I fixed the line you commented on and push 0.34.3 If that fixes it, please close this issue.

Also, I am collection setting for regression testing would you mind posting a sanitized version of your settings. Thanks.

**Comment by momiji** [comment]
Great, it works back :) This is sooo fast, this is very good ! I never put a comment on code before, I'm happy it worked so well...

I guess you want my config (english is not my mother tong, so I may understand badly), so here it is:

user settings:
```
{
    "sync-rsync.autoShowOutput": false,
    "sync-rsync.cygpath": "d:\\cygwin64\\bin\\cygpath.exe",
    "sync-rsync.delete": false,
    "sync-rsync.executable": "/bin/rsync",
    "sync-rsync.executableShell": "d:\\cygwin64\\bin\\bash.exe",
    "sync-rsync.notification": true,
    "sync-rsync.onSaveIndividual": true,
    "sync-rsync.onLoadIndividual": true,
    "sync-rsync.showProgress": false,
    "sync-rsync.flags": "rlptz",
}
```

workspace settings:
```
{
	"folders": [
		{
			"path": "project_folder"
		}
	],
	"settings": {
		"sync-rsync.shell": "/bin/ssh -p 22",
		"sync-rsync.remote": "root@1.2.3.4:/root/project_folder/",
		"sync-rsync.local": "D:\\devr\\project_folder\\",
		"sync-rsync.exclude": [
			".git",
			".vscode",
			".build/",
			"*~"
		]
	}
}
```

**Comment by momiji** [comment]
closing issue as this is solved. Thanks !
