### ISSUE TITLE
Failure to execute custom ssh command

### ISSUE THREAD

**Issue by kfir-drivenets** [thisboyiscrazy/vscode-rsync#71]
I tried to configure a custom shell command via the following config
```json
{
     "sync-rsync.shell": "ssh -p 2222 -l myuser"
}
```

I get the following error:
```bash
> rsync -nrlptzv -e ssh --progress --rsh="ssh -p 2222 -l myuser" --exclude=.git --exclude=.vscode /home/myuser/ myuser@myhost:/home/myuser/ 
rsync: Failed to exec ssh -p 2222 -l myuser: No such file or directory (2)
rsync error: error in IPC code (code 14) at pipe.c(85) [sender=3.1.2]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in IPC code (code 14) at io.c(235) [sender=3.1.2]
```

When I run the same command directly via bash everything works as expected.
I assume that this is some escaping related issue.

I'm using version 0.34.4 of the extension, vscode version 1.30.2

**Comment by thisboyiscrazy** [comment]
can you run in bash:

```which rsync```

Cygwin, flatpak, and WSL sometimes need the full path to ssh. What OS are you running?

**Comment by beeradmoore** [comment]
@thisboyiscrazy I have this issue as well. I'm running macOS 10.14.3, VSCode 1.31.1, Sync-Rsync 0.34.5.

My config looks like, 
```
{
    "sync-rsync.sites": [
        {
            "name": "somesite",
            "remotePath":"ec2-user@somesite.com:/var/www/somepath/",
            "shell": "/usr/bin/ssh -i /Users/someuser/.ssh/somekey.pem",
            "localPath":"/Users/someuser/somepath/",
            "options": [
                ["rsync-path", "sudo -Hu apache rsync"]
            ]
        }
    ]
}
```

Would output something like, 
```
> rsync -nrlptzv --rsync-path="sudo -Hu apache rsync" --progress --rsh="/usr/bin/ssh -i /Users/someuser/.ssh/somekey.pem" --exclude=.git --exclude=.vscode /Users/someuser/somepath/ ec2-user@somesite.com:/var/www/somepath/ 
rsync: Failed to exec /usr/bin/ssh -i /Users/someuser/.ssh/somekey.pem: No such file or directory (2)
rsync error: error in IPC code (code 14) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/pipe.c(86) [sender=2.6.9]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/io.c(453) [sender=2.6.9]
```

It will complain about my rsync-path issue later on, but I have the same issue if I remove it (though I think thats an issue with my server).

If I copy the command it attempts to run and put it in terminal it runs fine.

**Comment by coldmanck** [comment]
> (TL;DR; I think I fixed it, see EDIT2 at the bottom)
> 
> @thisboyiscrazy I have this issue as well. I'm running macOS 10.14.3, VSCode 1.31.1, Sync-Rsync 0.34.5.
> 
> My config looks like,
> 
> ```
> {
>     "sync-rsync.sites": [
>         {
>             "name": "somesite",
>             "remotePath":"ec2-user@somesite.com:/var/www/somepath/",
>             "shell": "/usr/bin/ssh -i /Users/someuser/.ssh/somekey.pem",
>             "localPath":"/Users/someuser/somepath/",
>             "options": [
>                 ["rsync-path", "sudo -Hu apache rsync"]
>             ]
>         }
>     ]
> }
> ```
> 
> Would output something like,
> 
> ```
> > rsync -nrlptzv --rsync-path="sudo -Hu apache rsync" --progress --rsh="/usr/bin/ssh -i /Users/someuser/.ssh/somekey.pem" --exclude=.git --exclude=.vscode /Users/someuser/somepath/ ec2-user@somesite.com:/var/www/somepath/ 
> rsync: Failed to exec /usr/bin/ssh -i /Users/someuser/.ssh/somekey.pem: No such file or directory (2)
> rsync error: error in IPC code (code 14) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/pipe.c(86) [sender=2.6.9]
> rsync: connection unexpectedly closed (0 bytes received so far) [sender]
> rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/io.c(453) [sender=2.6.9]
> ```
> 
> It will complain about my rsync-path issue later on, but I have the same issue if I remove it (though I think thats an issue with my server).
> 
> If I copy the command it attempts to run and put it in terminal it runs fine.
> 
> EDIT: Removing the shell and options command and adding my ssh info into my ~/.ssh/config file I can then connect just fine. I can't sync files because I need to run the remote rsync as apache which does currently work.
> 
> Ironically I used to use a shell script that'd run fswatch and rsync in order to do all of this. It looks like this.
> 
> ```
> #!/bin/sh
> 
> USER="xxx"
> SERVER="xxx"
> LOCAL_DIR="xxx"
> REMOTE_DIR="xxx"
> PEM_LOCATION="xxx"
> 
> # -I to force upload.
> code $LOCAL_DIR
> 
> #    --exclude="vendor/*" \
> fswatch -o $LOCAL_DIR | xargs -n1 -I{} rsync -O -avzh -e "ssh -i $PEM_LOCATION" \
>     --include=".htaccess" \
>     --exclude=".*" \
>     --exclude=".*/" \
>     --exclude="*.orig" \
>     --exclude="config.php" \
>     --exclude="composer.json" \
>     --exclude="composer.lock" \
>     --exclude="dev_privatekey.pem" \
>     --exclude="apple-app-site-association" \
>     --rsync-path="sudo -Hu apache rsync" $LOCAL_DIR $USER@$SERVER:$REMOTE_DIR
> ```
> 
> Its funny to see the command that is attempted to run is so similar to mine. The -e is the same as --rsh, and I am using the same --rsync-path as my script so its odd that it doesn't want to run correctly. I wonder if VSCode or at least its extensions is limited on what files it can access. I ran VSCode as root and it didn't change anything.
> 
> EDIT2: After reading the very bottom of the manual and adding
> 
> ```
> "executableShell": "/bin/bash",
> ```
> 
> to my settings it lets it execute all completely fine. Possibly the same issue as OP.

This saved my day. Thanks
