### ISSUE TITLE
Doesn't ask for password in WSL

### ISSUE THREAD

**Issue by umstek** [thisboyiscrazy/vscode-rsync#73]
It does not ask for the password, and sometimes even shows that jobs are running or even completed (but they are not). It also occasionally shows the error message 4294967295. 

Basically, how do I specify the password when I'm using WSL?

**Comment by thisboyiscrazy** [comment]
I have not found a way around that. You can either put it in your .ssh/config or use authorized keys.

Maybe I could write the extension to watch for the text for asking for a password them put up a input window.

I don't know what error 4294967295 can you post the whole output?

**Comment by thisboyiscrazy** [comment]
Try this `"sync-rsync.executable": "sshpass -p \"password\" rsync"`
