### ISSUE TITLE
You closed #57 but I suspect that it still doesn't work

### ISSUE THREAD

**Issue by lisegerd** [thisboyiscrazy/vscode-rsync#74]
Hi
Thank you for this extension. This is exactly what I was looking for! However, I cannot get "On Save Individual" to work with WSL. I get the notification that the file is synced and I do not get any error messages, but the file is not synced. If I use other of the extensions commands, it works, so I know for sure that my SSH and Rsync is working.

I looked into the source code and the description of the error in #57 fits perfectly. If the comparison "if(file.startsWith(path))" fails, the program will do exactly what it is actually doing: Do nothing and show a successful notification.

I also get the success notification when I save my preferences. This is a bit confusing as it is not in my specified path. In this case the "if(file.startsWith(path))" works correct, but the notification should not be shown. 

Configuration:
- Client: Windows 10 Pro with WSL and Ubuntu 18.04 LTS (up-to-date versions)
- Server: Ubuntu 18.04 LTS
- VS code 1.31.1
- sync-Rsync 0.34.4

Settings
    "sync-rsync.useWSL": true,
    "sync-rsync.remote": "xxx@server:/var/www/site/folder/",
    "sync-rsync.local": "/mnt/c/Users/xxx/Development/Folder/",
    "sync-rsync.notification": true,
    "sync-rsync.autoShowOutput": true,
    "sync-rsync.onSaveIndividual": true

**Comment by thisboyiscrazy** [comment]
Thanks for giving me the config and settings. It made debugging a lot easier.

You are correct, I had the fix in then took it out with some other code. 

I just pushed 0.34.5. I should fix the problem.

**Comment by lisegerd** [comment]
Thanks for an immediate respons. It seems to work now!
