### ISSUE TITLE
Sync Activity Bar settings?

### ISSUE THREAD

**Issue by JKawmi** [thisboyiscrazy/vscode-rsync#77]
Is this possible?  I don't just mean the position, I mean which icons are disabled and the order of the enabled ones.

**Comment by thisboyiscrazy** [comment]
Can you be a little more descriptive on what you are looking for?

**Comment by JKawmi** [comment]
This is how the activity bar looks on my main PC

![image](https://user-images.githubusercontent.com/13506188/53701475-2a2b9e80-3dfe-11e9-86a1-9fd54c722156.png)

And this is how it looks on a fresh install with sync enabled

![image](https://user-images.githubusercontent.com/13506188/53701480-36aff700-3dfe-11e9-86a5-9b831da9e2fc.png)

Notice the order and how many of them are showing, I know this is a 1st world problem kind of things but it would be nice to have.

**Comment by thisboyiscrazy** [comment]
I not sure this has to do with my extension. I have seen this before when upgrading vscode. try deleting `.vscode` in your home directory.

**Comment by JKawmi** [comment]
@thisboyiscrazy Oh my god, sorry apperently I can't read hahah I copied the wrong link of the extension in mind.
