### ISSUE TITLE
win10: The source and destination cannot both be remote.

### ISSUE THREAD

**Issue by LokLu** [thisboyiscrazy/vscode-rsync#79]
The source and destination cannot both be remote.
As I used the setting according to the windows notes.
Seems rsync will regard the local path with colon as remote path.
Any advice how to make the settings correctly?

**Comment by thisboyiscrazy** [comment]
You are trying the use a remote local path?

No it does not regard a local path with a colon as a remote path. Can you post your settings?

**Comment by LokLu** [comment]
I updated the "localPath" from "Y:\\luk\\" to "/cygdrive/y/luk/", and now it works.
I also saw your solution under another issue #5.
Maybe you can update it in the windows note about the "localPath" setting?

I came with a new issue, my settings are as following, but with "rsync return 12" error.
Settings:
	"settings": {
		"sync-rsync.sites": [
			{
				"localPath": "/cygdrive/y/luk/server/dgx/mydocker/",
				"remotePath": "luk@ip_address:/home/i2r/luk/scratch/mydocker/"
			}
		],
		"sync-rsync.onSaveIndividual": true,
		"sync-rsync.notification": true,
		"sync-rsync.cygpath": "C:\\cygwin64\\bin\\cygpath.exe",
		"sync-rsync.executableShell": "C:\\cygwin64\\bin\\bash.exe",
		"sync-rsync.executable": "/bin/rsync",
		"sync-rsync.shell": "/cygdrive/c/Windows/System32/OpenSSH/ssh",
		"sync-rsync.autoShowOutput": true,
		"sync-rsync.onSave": true
	}

Rsync output:
> /bin/rsync -rlptzv --progress --rsh="/cygdrive/c/Windows/System32/OpenSSH/ssh -i /cygdrive/c/Users/1/.ssh/id_ed25519" --exclude=.git --exclude=.vscode /cygdrive/y/luk/server/dgx/mydocker/ luk@ip_address:/home/i2r/luk/scratch/mydocker/ 
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [Receiver=3.1.1]
Warning: Identity file /cygdrive/c/Users/1/.ssh/id_ed25519 not accessible: No such file or directory.
rsync: safe_read failed to read 4 bytes [sender]: Connection reset by peer (104)
rsync error: error in rsync protocol data stream (code 12) at io.c(276) [sender=3.1.2]

Seems I didn't set the ssh key well, but no idea well to add the key info.
Would you please advice?
Thanks!

**Comment by LokLu** [comment]
I also tried 
"sync-rsync.shell": "/cygdrive/c/Windows/System32/OpenSSH/ssh -I /cygdrive/c/Users/1/.ssh/id_ed25519",
but got small error

**Comment by thisboyiscrazy** [comment]
Is there anyting in `/cygdrive/c/Users/1/.ssh/id_ed25519`?

**Comment by LokLu** [comment]
Yes, there is a private key there as part of it shown in the below pic.
![image](https://user-images.githubusercontent.com/24246633/54484772-6dc6e380-48a7-11e9-9aa6-c92a1d5e18e1.png)

**Comment by thisboyiscrazy** [comment]
Looks like you are mixing cygwin and WSL. Pick on or the other. WSL would be your best bet.

**Comment by thisboyiscrazy** [comment]
Try something like this:

```
{
  "sync-rsync.sites": [
    {
      "localPath": "/cygdrive/c/Users/user/path/",
      "remotePath": "user@server:/path/",
      "shell":"/bin/ssh -i /home/user/.ssh/id_rsa"
    }
  ],
  "sync-rsync.onSaveIndividual": true,
  "sync-rsync.notification": true,
  "sync-rsync.executableShell": "C:\\cygwin64\\bin\\bash.exe",
  "sync-rsync.executable": "/bin/rsync",
  "sync-rsync.autoShowOutput": true,
  "sync-rsync.onSave": true
}
```

**Comment by thisboyiscrazy** [comment]
@LokLu is this issue closed?

**Comment by lukk47** [comment]
Hi, @thisboyiscrazy, thanks for your reply, issue closed!
