### ISSUE TITLE
Feature request: sync-rsync.afterSync

### ISSUE THREAD

**Issue by jacobweber** [thisboyiscrazy/vscode-rsync#80]
Could we have a global default for the afterSync config setting, e.g. `sync-rsync.afterSync`? Right now it looks like it can only be set inside `sync-rsync.sites`.

**Comment by thisboyiscrazy** [comment]
Good idea.

**Comment by thisboyiscrazy** [comment]
Should be in 0.35.0

**Comment by jacobweber** [comment]
@thisboyiscrazy Thanks for the update. But I'm still seeing that `afterSync` as well as the new options (`postSyncUp` etc.) are only available inside the `sync-rsync.sites` array. I'd like to set them as workspace-level or user-level settings, like I can do for `sync-rsync.options` etc.

(Use case: I want to play a sound after syncing, using `/usr/bin/afplay` on the Mac. I typically have rsync configured at the workspace level, so my workspace `settings.json` has things like `sync-rsync.remote` etc.)

**Comment by thisboyiscrazy** [comment]
Values not in `sites` are considered defaults. So just create a site with just `postyncUp` in it and it should work.

```
  "sync-rsync.remote":"remote",
  "sites: [
    {
      "postSyncUp":"doStuff"
    }
  ]
````

I work on adding them to the defaults.

**Comment by jacobweber** [comment]
Ah, I didn't realize that. I had to use `"sync-rsync.sites":`, but this worked, both in the workspace and the user configs. Thanks!

**Comment by chaddjohnson** [comment]
Hey guys,

I'm having trouble getting `postSyncUp` to work. Here is my config:

```
"settings": {
  "sync-rsync.sites": [
    {
      "name": "wordpress-dev",
      "localPath": "/Users/chad/development/projects/project-name/app/src/",
      "remotePath": "wordpress@server:/home/wordpress/www/wordpress-dev/wp-content/plugins/project-name/",
      "upOnly": true,
      "include": ["**/.php"],
      "postSyncUp": ["ssh", "wordpress@server", "'", "sed", "-i", "-e", "s/APP_URL/mydomain.ngrok.io/", "/home/wordpress/www/wordpress-dev/wp-content/plugins/project-name/project-name.php", "'"]
    }
  ],
  "sync-rsync.onSaveIndividual": true,
  "sync-rsync.onLoadIndividual": true
}
```

When I save a file there is no output related to postSyncUp:

```
Tue Oct 29 2019 14:11:54 GMT-0400 (Eastern Daylight Time) syncing
> rsync -rlptzv --progress --include=**/.php --exclude=.git --exclude=.vscode /Users/chad/development/projects/project-name/app/src/project-name.php wordpress@wordpress:/home/wordpress/www/wordpress-dev/wp-content/plugins/project-name/project-name.php 
building file list ... 
 0 files...
1 file to consider
wc-fulfillment-print-on-demand.php
         700  87%    0.00kB/s    0:00:00
         800 100%   97.66kB/s    0:00:00 (xfer#1, to-check=0/1)

sent 111 bytes  received 54 bytes  66.00 bytes/sec
total size is 800  speedup is 4.85
```

I have tried using `afterSync` in place of `postSyncUp`, as well.

I'm on 0.36.0.

I noticed there is no mention of `postSyncUp` in the built extension:

```
hyperion:vscode-ext.sync-rsync-0.36.0 chad$ cat out/extension.js | grep postSyncUp
hyperion:vscode-ext.sync-rsync-0.36.0 chad$ 
```
