### ISSUE TITLE
Extension doesn't load on Windows

### ISSUE THREAD

**Issue by Toastgeraet** [thisboyiscrazy/vscode-rsync#81]
See attached Developer logs. Commands are still listed in Command menu but always "not found" by VSCODE when executed.

First occured after disabling extension for the first time and ever since. Uninstall and reinstall didnt help.

[-1553070027381.log](https://github.com/thisboyiscrazy/vscode-rsync/files/2987110/-1553070027381.log)

**Comment by thisboyiscrazy** [comment]
Are you using cygwin? can you check the value of `sync-rsync.cygpath`

**Comment by Toastgeraet** [comment]
I am using the cygpath.exe without cygwin.

it works flawlessly inside all my shells: powershell, cmd, git-bash.

i put the absolute path into sync-rsync.cygpath.
i tried cygpath format as well as windows format.


On 20 March 2019 21:33:17 GMT+01:00, thisboyiscrazy <notifications@github.com> wrote:
>Are you using cygwin? can you check the value of `sync-rsync.cygpath`
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/thisboyiscrazy/vscode-rsync/issues/81#issuecomment-475016641

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by thisboyiscrazy** [comment]
How are you using cygpath without cygwin?
