### ISSUE TITLE
workspaceRoot is deprecated and should be replaced with workspaceFolder

### ISSUE THREAD

**Issue by iwagner-inmar** [thisboyiscrazy/vscode-rsync#82]
On a multi-folder project, if you use relative source paths, it will always use the first folder in your project. If workspaceFolder was used instead, you could use relative paths to all project folders.

See: https://code.visualstudio.com/docs/editor/variables-reference#_why-isnt-workspaceroot-documented

**Comment by thisboyiscrazy** [comment]
Nice catch hopefully I will get some time tomorrow to work on this.
