### ISSUE TITLE
Need wslpath otherwise rsync-sync will not load

### ISSUE THREAD

**Issue by gojanb** [thisboyiscrazy/vscode-rsync#87]
If anybody else have problem getting rsync-sync started.

I have an "old" version of Windows (Version 1709 OS Build 16299) and in this version the command "wslpath" is missing. It was introduced in OS Build 17046.
It is no problem installing rsync-sync but when trying to use it nothing happens. When starting VSCode in debug mode I found the following error in the log:
Issue:/bin/bash: wslpath: command not found

After installing wslpath for older versions of WSL (https://github.com/laurent22/wslpath) everything is working.

**Comment by thisboyiscrazy** [comment]
Yeah, it's hard because Microsoft changed WSL, I will update the documentation. Thanks.
