### ISSUE TITLE
Output keeps stealing focus from editor window.

### ISSUE THREAD

**Issue by miaulalala** [thisboyiscrazy/vscode-rsync#89]
MacOS 10.14.3

VSCode Version 1.31.1 (1.31.1).

Settings:

`"sync-rsync.local": "/Users/xxx/xxx/webapp/",
    "sync-rsync.remote": "xxx@vxxx.com:/var/www/xxx/xxx/webapp/",
    "sync-rsync.showProgress" : true,
    "sync-rsync.autoShowOutput": true,
    "sync-rsync.executableShell": "/bin/bash",
    "sync-rsync.exclude":[
        "/Users/xxx/xxx/webapp/application/vendor/*",
        "/Users/xxx/xxx/webapp/.settings",
        "/Users/xxx/xxx/webapp/.git/*",
        "/Users/xxx/xxx/webapp/resources/css/*.css"
    ],
    "sync-rsync.options":  
    [
        [ "verbose" ],
        [ "progress" ],
        [ "itemize-changes" ],
        [ "times" ]
    ],`

If autoShowOutput is set to true, the Output window steals focus from the editor and puts the cursor at the end of the text output.

**Comment by thisboyiscrazy** [comment]
This looks like it is an issue with vscode and not the plugin.
