### ISSUE TITLE
[Q] How can we specify the passphrase for key?

### ISSUE THREAD

**Issue by pulkitsinghal** [thisboyiscrazy/vscode-rsync#9]
My key is protected with a passphrase so I keep running into the following error in VSCode (Visual Studio):

```
Permission denied, please try again.
ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
Permission denied (publickey,password).
```

How can I get around this?

**Comment by thisboyiscrazy** [comment]
Good question I'll look into it

**Comment by thisboyiscrazy** [comment]
Can verify if /usr/X11R6/bin/ssh-askpass exist?

**Comment by pulkitsinghal** [comment]
Good catch, the directory exists `/usr/X11R6/bin/` but not the binary for `ssh-askpass`

But looking beyond that, is there a silent way where it doesn't prompt me but I can specify the passphrase as part of configuration setup?

**Comment by thisboyiscrazy** [comment]
It does not seem that way. SSH does not allow for specifying the rsa passphrase on the command line.

It might get you in the correct direction: https://linux.die.net/man/1/ssh-agent
