### ISSUE TITLE
A specific file is not synced on save while all other are

### ISSUE THREAD

**Issue by gabriel-vanzandycke** [thisboyiscrazy/vscode-rsync#90]
For a reason I don't understand, a specific file (`model.py`) is not synced on save, while all other files (`util.py`, `provision.py`, ...) are.
If I run the "sync Local to Remote" command, the file is uploaded correctly: see OUTPUT tab below
```
> rsync -rlptzP --progress --include=external/*.py --exclude=.git --exclude=.gitmodules --exclude=.vscode --exclude=__pycache__ --exclude=external /home/user/local-folder/ user@remote:~/remote-folder/ 
sending incremental file list
./
model.py

          1,281   9%    0.00kB/s    0:00:00  
         13,261 100%    5.71MB/s    0:00:00 (xfr#1, to-chk=63/71)
```
But when I edit and save the file, nothing appears on the OUTPUT tab.

**Sync-Rsync version:** 0.34.7
**vscode version:** 1.32.3
**OS:** Ubuntu 18.04 up-to-date

my `settings.xml` is
```
{
    "sync-rsync.remote": "user@remote:~/remote-folder/",
    "sync-rsync.flags": "rlptzP",
    //"sync-rsync.delete": true,
    "sync-rsync.exclude": [
        ".git",
        ".gitmodules",
        ".vscode",
        "__pycache__",
        "external"
    ],
    "sync-rsync.include": [
        "external/*.py"
    ],
    //"sync-rsync.autoShowOutput": true,
    "sync-rsync.executableShell": "/bin/bash",
    "sync-rsync.onSaveIndividual": true
}
```

Files have exactly same attributes
```
$ lsattr model.py
--------------e--- model.py
$ lsattr utils.py
--------------e--- utils.py
```

**Comment by thisboyiscrazy** [comment]
This is very strange. I will try and replicate it. What directory are `model.py`, `util.py` `provision.py` relative the `workspaceFolder`?

**Comment by gabriel-vanzandycke** [comment]
They are all 3 at the root of my VSCode project. The real folder name is `DL` (both on the local and the remote of course)
