### ISSUE TITLE
onSaveIndividual not working with non absolute path for local

### ISSUE THREAD

**Issue by ludvikbrodl** [thisboyiscrazy/vscode-rsync#92]
Using the following settings will render onSaveIndividual useless.  
```
 "sync-rsync.sites": [
      {
        "localPath": "~/temp/my_synced_dir/",
        "remotePath": "username@server:/dir_to_sync_to/"
      }
]
```
Can be fixed by using absolute path for localPath instead; i.e: `/home/the_user/temp/my_synced_dir/`

**Comment by thisboyiscrazy** [comment]
Try settings `"sync-rsync.executableShell": "bash"`

**Comment by ludvikbrodl** [comment]
Didn't help, the executable was already set to /bin/bash. Change to `bash` with no difference in behaviour.

Here is my full workspace settings file. Using Redhat 7.6
```
{
  "folders": [
    {
      "path": "."
    }
  ],
  "settings": {
    "files.exclude": {
      "**/data": false
    },
    "sync-rsync.sites": [
      {
        "localPath": "~/temp/local_dir/",
        "remotePath": "lbrodl@remote_server:/remote_dir/src/"
      }
    ],
    "sync-rsync.exclude": [".git", ".vscode"],
    "sync-rsync.onSaveIndividual": true,
    "sync-rsync.onSave": false,
    "sync-rsync.autoShowOutputOnError": true,
    "sync-rsync.executable": "rsync",
    "sync-rsync.executableShell": "bash",
    "sync-rsync.flags": "rlptzvO"
  }
}
```

**Comment by thisboyiscrazy** [comment]
I tried those setting, I still can not replicate it. There should be an error in `Sync-Rsync` output. can you post that? Thanks.

**Comment by ludvikbrodl** [comment]
There is no output at all when i use the path with `~`, when using the absolute path there is output as expected. It's like rsync doesn't detect that the file has changed at all and thus doesn't trigger a rsync.

**Comment by thisboyiscrazy** [comment]
Oh, I see the problem. `~` is shell specific and on save I check if the path of the file begins with any `localPath`. I also don't do variable expansion e.g. `$HOME`. Just doing `${workspaceRoot}` has caused problems.

There is also no consistent way to call out to `executableShell` and get the path expanded.

So I did not think I am going to fix this. I will update the documentation.
