### ISSUE TITLE
Bug: rsync is executed even though the saved file is not in any of the "localPath"

### ISSUE THREAD

**Issue by netw0rkf10w** [thisboyiscrazy/vscode-rsync#93]
Hello,

After re-installing the extension, I observed a bug that did not exist in the previous version (I don't remember which version was that).

My settings look like this:

        "sync-rsync.autoShowOutput": true,
        "sync-rsync.onSave": true,
        "sync-rsync.onSaveIndividual": true,
        "sync-rsync.sites": [
            {
                "localPath": "/Users/username/A/",
                "remotePath": "ubuntu@xx.xxx.xx:/home/ubuntu/A/"
            },
            {
                "localPath": "/Users/username/B/",
                "remotePath": "ubuntu@xx.xxx.xx:/home/ubuntu/B/"
            }
        ]

Now if I open a folder `/Users/username/C/`, modify a file, press Save, then `rsync` is executed. This is not expected because `/Users/username/C/` is not among the configured local paths.

Could you please fix this?

Thank you so much!

**Comment by thisboyiscrazy** [comment]
Yes hopefully Tuesday I can look into it.

**Comment by thisboyiscrazy** [comment]
`"sync-rsync.onSave": true` and `sync-rsync.onSaveIndividual": true` are kind of mutial exclusive.

One syncs everything when any file is saved. The other only the changed file. You want `sync-rsync.onSaveIndividual": true`
