### ISSUE TITLE
remotePath splices the vscode install path by default?

### ISSUE THREAD

**Issue by hzgoin** [thisboyiscrazy/vscode-rsync#95]
```
{
	"folders": [
		{
			"path": "D:\\projects\\my_project"
		}
	],
	"settings": {
		"sync-rsync.onSaveIndividual": true,
		"sync-rsync.local": "/",
		"sync-rsync.remote": "myip::mymod",
		"sync-rsync.useWSL": true,
		// "sync-rsync.executable": "rsync"
	}
}
```
`rsync -rlptzv --progress --exclude=.git --exclude=.vscode /mnt/d/projects/my_project/wmtest /mnt/c/Users/WANGME~1/AppData/Local/Programs/Microsoft VS Code/myip::mymod/mnt/d/projects/my_project/wmtest`

**Comment by thisboyiscrazy** [comment]
Interesting, let me look into it. Also thanks providing the setting is helpfull

**Comment by hzgoin** [comment]
> Interesting, let me look into it. Also thanks providing the setting is helpfull

anything progress？

**Comment by thisboyiscrazy** [comment]
I know what the problem is, I just have to fix it. I'll try and get to it today.

**Comment by hzgoin** [comment]
> I know what the problem is, I just have to fix it. I'll try and get to it today.

thx，iam looking forward to your update

**Comment by thisboyiscrazy** [comment]
Try this:
```
{
	"folders": [
		{
			"path": "D:\\projects\\my_project\\"
		}
	],
	"settings": {
		"sync-rsync.onSaveIndividual": true,
		"sync-rsync.useWSL": true,
		"sync-rsync.sites":[
			{
				"localPath": "/mnt/d/projects/my_project/",
				"remotePath": "myip::mymod",
			},
		]
	}
}
```

**Comment by hzgoin** [comment]
> Try this:
> 
> ```
> {
> 	"folders": [
> 		{
> 			"path": "D:\\projects\\my_project\\"
> 		}
> 	],
> 	"settings": {
> 		"sync-rsync.onSaveIndividual": true,
> 		"sync-rsync.useWSL": true,
> 		"sync-rsync.sites":[
> 			{
> 				"localPath": "/mnt/d/projects/my_project/",
> 				"remotePath": "myip::mymod",
> 			},
> 		]
> 	}
> }
> ```

something seems to be working, but there still have problems.
now the command executed, which output in the terminal, is as follows.
```
rsync -rlptzv --progress --exclude=.git --exclude=.vscode /mnt/d/projects/my_project/wmtest /mnt/c/Users/WANGME~1/AppData/Local/Programs/Microsoft VS Code/myip::mymod/wmtest
```
it looks like that the program treats the remotePath as a local relative path not a remote rsync service.

**Comment by thisboyiscrazy** [comment]
Can you post your current settings.

**Comment by hzgoin** [comment]
> Can you post your current settings.

my setting is same as what you suggested.

i try to read the impletmantion code and find this.
[` site.remotePath = this.translatePath(site.remotePath);`](https://github.com/thisboyiscrazy/vscode-rsync/blob/90ae7c488fa2a478cc385a5619fe4eba847dbbe7/src/Config.ts#L123)

does  remotePath needed to be converted?

**Comment by hzgoin** [comment]
> > Can you post your current settings.
> 
> my setting is same as what you suggested.
> 
> i try to read the impletmantion code and find this.
> [` site.remotePath = this.translatePath(site.remotePath);`](https://github.com/thisboyiscrazy/vscode-rsync/blob/90ae7c488fa2a478cc385a5619fe4eba847dbbe7/src/Config.ts#L123)
> 
> does remotePath needed to be converted?

i comment this line and it work for me

**Comment by thisboyiscrazy** [comment]
I thought I commented that out. I'll get a version with that comment out soon.

**Comment by thisboyiscrazy** [comment]
Version 0.36.0 has the line removed.
