### ISSUE TITLE
Allow to sync to multiple remote locations

### ISSUE THREAD

**Issue by adaitche** [thisboyiscrazy/vscode-rsync#99]
It would be great if it were possible to sync to multiple remote locations. Maybe the `remote` setting could accept a comma separated string, e.g.

```
"sync-rsync.remote": "user@host1:path, user@host2:path"
```

This would support doing work on two or more remote servers. Currently, every time one wants to execute the code on a different server, one has to edit the settings to sync the code changes. If multiple remotes were supported, this workflow would be much more smooth.

**Comment by thisboyiscrazy** [comment]
This is possible if you setup multiple sites with the same local
```
{
    "sync-rsync.sites": [
        {
            "remotePath":"user@host1:path"
        },
        {
            "remotePath":"user@host2:path"
        }
    ]
}
```

This assume the local path is the current folder for both sites, otherwise you can add a `local` to each site.

**Comment by adaitche** [comment]
Works like a charm. Thanks a lot!
